# Generated by Django 3.2 on 2021-04-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_pw', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=5)),
            ],
        ),
    ]
